/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module control_6 (
    input [1:0] direction,
    input [3:0] state,
    input [3:0] cur_level,
    output reg [1:0] sel_new_pos,
    output reg [5:0] alufn,
    output reg sel_level,
    output reg sel_check,
    output reg sel_map,
    output reg fill_border_red,
    output reg fill_border_green,
    output reg show_splashscreen,
    output reg hide_screen,
    output reg [19:0] text
  );
  
  
  
  reg [3:0] cur_level_lastdigit;
  
  reg [19:0] display_level;
  
  always @* begin
    sel_level = 1'h0;
    sel_check = 1'h0;
    sel_map = 1'h0;
    fill_border_green = 1'h0;
    fill_border_red = 1'h0;
    show_splashscreen = 1'h0;
    hide_screen = 1'h0;
    cur_level_lastdigit = (cur_level > 4'h9) ? cur_level - 4'ha : cur_level;
    if (cur_level > 4'h9) begin
      display_level = {1'h0 + cur_level_lastdigit, 5'h01, 5'h0b, 5'h0e};
    end else begin
      display_level = {1'h0 + cur_level, 5'h00, 5'h0b, 5'h0e};
    end
    text = 20'h739ce;
    
    case (state)
      1'h0: begin
        sel_level = direction[0+0-:1];
        sel_new_pos = 1'h0;
        alufn = 6'h00;
        show_splashscreen = 1'h1;
      end
      1'h1: begin
        sel_level = direction[0+0-:1];
        sel_new_pos = 1'h0;
        alufn = 6'h00;
        text = display_level;
      end
      2'h2: begin
        sel_level = 1'h0;
        sel_new_pos = 1'h0;
        alufn = 6'h00;
        text = display_level;
      end
      2'h3: begin
        sel_level = 1'h0;
        sel_new_pos = direction;
        sel_check = 1'h0;
        sel_map = 1'h0;
        alufn = 6'h33;
      end
      3'h4: begin
        sel_level = 1'h0;
        sel_new_pos = direction;
        sel_check = 1'h0;
        sel_map = 1'h1;
        alufn = 6'h33;
      end
      3'h5: begin
        sel_level = 1'h0;
        sel_new_pos = direction;
        sel_check = 1'h1;
        alufn = 6'h18;
      end
      3'h6: begin
        sel_level = 1'h0;
        sel_new_pos = direction;
        sel_check = 1'h1;
        alufn = 6'h1e;
      end
      3'h7: begin
        sel_level = 1'h0;
        sel_new_pos = direction;
        alufn = 6'h00;
        fill_border_green = 1'h1;
        text = 20'h63d8e;
      end
      4'h8: begin
        sel_level = 1'h0;
        sel_new_pos = 1'h0;
        alufn = 6'h00;
        fill_border_red = 1'h1;
        text = 20'h63d6d;
      end
      4'h9: begin
        sel_level = 1'h0;
        sel_new_pos = 1'h0;
        alufn = 6'h00;
        text = 20'h8460e;
      end
      default: begin
        sel_level = 1'bz;
        sel_new_pos = 1'bz;
        alufn = 6'h00;
        text = 20'h8c631;
      end
    endcase
  end
endmodule
