/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module map_rom_19 (
    input [1:0] level_adr,
    output reg [35:0] map_a,
    output reg [35:0] map_b,
    output reg [5:0] sp_a,
    output reg [5:0] sp_b,
    output reg [5:0] ep_a,
    output reg [5:0] ep_b
  );
  
  
  
  always @* begin
    
    case (level_adr)
      1'h0: begin
        map_a = 36'hfe1d6197f;
        map_b = 36'hfe1d6197f;
        sp_a = 6'h21;
        sp_b = 6'h21;
        ep_a = 6'h0c;
        ep_b = 6'h0c;
      end
      1'h1: begin
        map_a = 36'hfe5c6b87f;
        map_b = 36'hfe5c6587f;
        sp_a = 6'h0c;
        sp_b = 6'h0c;
        ep_a = 6'h09;
        ep_b = 6'h09;
      end
      2'h2: begin
        map_a = 36'hfe1a73a7f;
        map_b = 36'hfe197397f;
        sp_a = 6'h09;
        sp_b = 6'h09;
        ep_a = 6'h24;
        ep_b = 6'h21;
      end
      2'h3: begin
        map_a = 36'hfe186187f;
        map_b = 36'hfe1a6187f;
        sp_a = 6'h13;
        sp_b = 6'h21;
        ep_a = 6'h1c;
        ep_b = 6'h0c;
      end
      default: begin
        map_a = 36'hfe1d6197f;
        map_b = 36'hfe986987f;
        sp_a = 6'h0c;
        sp_b = 6'h0c;
        ep_a = 6'h21;
        ep_b = 6'h21;
      end
    endcase
  end
endmodule
