/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module map_to_display_3 (
    input [5:0] tp_a,
    input [5:0] ep_a,
    input [35:0] map_a,
    input [5:0] tp_b,
    input [5:0] ep_b,
    input [35:0] map_b,
    input fill_border_green,
    input fill_border_red,
    input slowclk,
    input show_splashscreen,
    output reg [63:0] red,
    output reg [63:0] green
  );
  
  
  
  integer x;
  
  integer y;
  
  always @* begin
    green = 64'h0000000000000000;
    red = 64'h0000000000000000;
    for (x = 1'h1; x <= 3'h4; x = x + 1) begin
      for (y = 1'h1; y <= 3'h4; y = y + 1) begin
        red[(y + 1'h1)*8+(x + 2'h3)*1+0-:1] = map_a[(y)*6+(x)*1+0-:1];
        red[(y + 1'h1)*8+(x - 1'h1)*1+0-:1] = map_b[(y)*6+(x)*1+0-:1];
      end
    end
    green[(tp_a[0+2-:3] + 1'h1)*8+(tp_a[3+2-:3] + 2'h3)*1+0-:1] = 1'h1;
    green[(tp_b[0+2-:3] + 1'h1)*8+(tp_b[3+2-:3] - 1'h1)*1+0-:1] = 1'h1;
    red[(ep_a[0+2-:3] + 1'h1)*8+(ep_a[3+2-:3] + 2'h3)*1+0-:1] = 1'h1;
    red[(ep_b[0+2-:3] + 1'h1)*8+(ep_b[3+2-:3] - 1'h1)*1+0-:1] = 1'h1;
    green[(ep_a[0+2-:3] + 1'h1)*8+(ep_a[3+2-:3] + 2'h3)*1+0-:1] = 1'h1;
    green[(ep_b[0+2-:3] + 1'h1)*8+(ep_b[3+2-:3] - 1'h1)*1+0-:1] = 1'h1;
    if (fill_border_green & slowclk) begin
      green[0+7-:8] = 8'hff;
      green[8+7-:8] = 8'hff;
      green[48+7-:8] = 8'hff;
      green[56+7-:8] = 8'hff;
    end
    if (fill_border_red) begin
      red[0+7-:8] = 8'hff;
      red[8+7-:8] = 8'hff;
      red[48+7-:8] = 8'hff;
      red[56+7-:8] = 8'hff;
    end
    if (show_splashscreen) begin
      green = 64'h0000e04040400000;
      red = 64'h00000015150a0000;
    end
  end
endmodule
