/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module check_3 (
    input clk,
    input check_win,
    input [15:0] value,
    output reg [15:0] r0,
    output reg [15:0] r1,
    output reg [15:0] r2
  );
  
  
  
  reg [15:0] M_reg_r0_d, M_reg_r0_q = 1'h0;
  reg [15:0] M_reg_r1_d, M_reg_r1_q = 1'h0;
  reg [15:0] M_reg_r2_d, M_reg_r2_q = 1'h0;
  
  always @* begin
    M_reg_r0_d = M_reg_r0_q;
    M_reg_r1_d = M_reg_r1_q;
    M_reg_r2_d = M_reg_r2_q;
    
    M_reg_r0_d = M_reg_r0_q;
    M_reg_r1_d = M_reg_r1_q;
    M_reg_r2_d = M_reg_r2_q;
    if (check_win == 1'h0) begin
      M_reg_r1_d = value;
    end
    if (check_win == 1'h1) begin
      M_reg_r2_d = value;
    end
    if (check_win == 2'h2) begin
      M_reg_r0_d = value;
    end
    r0 = M_reg_r0_q;
    r1 = M_reg_r1_q;
    r2 = M_reg_r2_q;
  end
  
  always @(posedge clk) begin
    M_reg_r0_q <= M_reg_r0_d;
    M_reg_r1_q <= M_reg_r1_d;
    M_reg_r2_q <= M_reg_r2_d;
  end
  
endmodule
