/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module matrix_decoder_6 (
    input [5:0] curr_tp,
    input [35:0] mapdata,
    input [1:0] sel_new_pos,
    output reg [5:0] new_tp
  );
  
  
  
  reg [2:0] x_pos;
  
  reg [2:0] y_pos;
  
  reg [5:0] tpmux;
  
  reg out;
  
  always @* begin
    if (sel_new_pos == 1'h0) begin
      tpmux = curr_tp - 6'h01;
    end else begin
      if (sel_new_pos == 1'h1) begin
        tpmux = curr_tp + 6'h01;
      end else begin
        if (sel_new_pos == 2'h2) begin
          tpmux = curr_tp + 6'h08;
        end else begin
          if (sel_new_pos == 2'h3) begin
            tpmux = curr_tp - 6'h08;
          end else begin
            tpmux = 1'bz;
          end
        end
      end
    end
    x_pos = tpmux[3+2-:3];
    y_pos = tpmux[0+2-:3];
    out = mapdata[(y_pos)*6+(x_pos)*1+0-:1];
    if (out == 1'h1) begin
      new_tp = curr_tp;
    end else begin
      new_tp = tpmux;
    end
  end
endmodule
